import express from "express";
import path from "path";
import { router as auth } from "./controllers/auth";
import { router as register } from "./controllers/register";
import { router as rider } from "./controllers/rider";
import { router as senditem } from "./controllers/senditem";
import { router as shipments } from "./controllers/shipments";
import { router as users } from "./controllers/users";
import { router as rideraccepted } from "./controllers/rideraccepted";
export const app = express();
app.use(express.json({ limit: "80mb" }));
app.use(express.urlencoded({ extended: true, limit: "80mb" }));
app.use("/uploads", express.static(path.join(process.cwd(), "uploads")));
app.use("/senditem", senditem);
app.use("/users", users);
app.use("/login", auth);
app.use("/register", register);
app.use("/shipments", shipments);
app.use("/riders", rider);
app.use("/riders/accepted", rideraccepted);
app.use((req, res) => {
    res.status(404).json({ message: "Not Found" });
});
